user_config : 

model_name : collaborative_filtering

data : data/clicks.csv

max_sampled : 10000

n_epoch : 30

mlflow : 
  experiment_name : recommenders
  run_name : collaborative_filtering_lightfm_10000
  












